services:
  - type: web
    name: rebecca-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_TOKEN
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
